getProductList:
  handler: src/products/functions/getProductList.handler
  events:
    - http:
        path: /products
        method: GET
        authorizer: ${self:custom.authorizer.users}
createProduct:
  handler: src/products/functions/createProduct.handler
  events:
    - http:
        path: /product/new
        method: POST
        authorizer: ${self:custom.authorizer.users}
getProductDetail:
  handler: src/products/functions/getProductDetail.handler
  events:
    - http:
        path: /products/{productId}
        method: GET
        authorizer: ${self:custom.authorizer.users}
editProductDetail:
  handler: src/products/functions/editProduct.handler
  events:
    - http:
        path: /products/{productId}
        method: PATCH
        authorizer: ${self:custom.authorizer.users}
deleteProduct:
  handler: src/products/functions/deleteProduct.handler
  events:
    - http:
        path: /products/{productId}
        method: DELETE
        authorizer: ${self:custom.authorizer.users}