service: SkyShopping

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  - ${file(./src/user/user.yml)}
  - ${file(./src/products/products.yml)}
  - ${file(./src/auth/auth.yml)}
  - ${file(./src/cart/cart.yml)}
  - ${file(./src/order/order.yml)}
  - ${file(./src/chat/chat.yml)}

custom:
  stage: ${opt:stage, self:provider.stage}
  authorizer:
    users:
      name: authorizerUser
      type: TOKEN
      identitySource: method.request.header.Authorization
      identityValidationExpression: Bearer (.*)
